version: "3"

services:
  db:
    image: mysql:5.7
    container_name: mysql_wordpress
    # volumes:
      # - "./db_data:/var/lib/mysql"
    restart: always
    # ports:
    #   - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: wordpress_root_password
      MYSQL_DATABASE: wordpress_db
      MYSQL_USER: wordpress_user
      MYSQL_PASSWORD: wordpress_password

  wordpress:
    container_name: wordpress
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "8888:80"
    restart: always
    # volumes:
    #   - "./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini"
    volumes:
      - "./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini"
      # - "./wordpress:/var/www/html"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress_user
      WORDPRESS_DB_PASSWORD: wordpress_password
      WORDPRESS_DB_NAME: wordpress_db
volumes:
  # db_data: {}
  wordpress:
  db_data:
